config/routes.rb
Rails.application.routes.draw do
  resources :flats
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :set_flat, only: [:show, :edit, :update, :destroy]

  def index
    @flats = Flat.all
  end

  def show
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
      if @flat.save
        redirect_to @flat
      else
        render :new
      end
  end

  def edit
  end

  def update
    @flat.update(flat_params)

    # redirect to the restaurant show page
    redirect_to flat_path(@flat)
  end

  def destroy
    @flat.destroy

    # redirect to the index
    redirect_to flats_path
  end

private
  def set_flat
    @flat = Flat.find(params[:id])
  end

  def flat_params
      params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/_form.html.erb
<%= simple_form_for(@flat) do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :description %>
  <%= f.input :price_per_night %>
  <%= f.input :number_of_guests %>
  <%= f.submit "add Flat", class: "btn btn-primary" %>
<% end %>

app/views/flats/edit.html.erb
<h1>Edit Restaurant</h1>
<%= render 'form' %>

app/views/flats/index.html.erb
<h1>Flats</h1>

<%= link_to 'New Flat', new_flat_path %>


<% @flats.each do |flat| %>
  <div class="flat">
    <div class="content">
      <h3><%= flat.name %></h3>
      <p><%= flat.description%></p>
      <i class="fas fa-user-friends"><%= flat.number_of_guests %></i>
      <i class="fas fa-euro-sign"><%= flat.price_per_night %></i>
    </div>
    <div class="link">
      <p>
        <%= link_to "show more", flat_path(flat) %>
        <%= link_to 'Delete', flat_path(flat), method: :delete, data: { confirm: 'Are you sure?' } %>
        </p>

    </div>
  </div>
<% end %>

app/views/flats/new.html.erb
<h1>Create New Restaurant</h1>
<%= render 'form' %>

app/views/flats/show.html.erb
<p><%= link_to "edit flat", edit_flat_path(@flat) %></p>
<h1> <%= @flat.name %></h1>

<p><%= link_to "See all flats", flats_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>